import type {
  CurrentObservation,
  StationMeta,
  ForecastDay,
  HourlyForecast,
  StationStatus,
} from '../types/weather';
import {
  PrecipitationType,
  PressureTrend,
} from '../types/weather';

export const stubStationMeta: StationMeta = {
  station_id: 12345,
  name: 'Backyard Weather Station',
  latitude: 30.2672,
  longitude: -97.7431,
  elevation: 149,
  timezone: 'America/Chicago',
  firmware_revision: 'v1.7.2',
  serial_number: 'ST-00012345',
  device_id: 67890,
};

export const stubCurrentObservation: CurrentObservation = {
  timestamp: Date.now() / 1000,
  windLull: 0.5,
  windAvg: 2.3,
  windGust: 4.8,
  windDirection: 225,
  windSampleInterval: 6,
  stationPressure: 1013.25,
  airTemperature: 23.4,
  relativeHumidity: 62,
  illuminance: 45000,
  uvIndex: 5.2,
  solarRadiation: 612,
  rainAccumulated: 0,
  precipitationType: PrecipitationType.None,
  lightningStrikeAvgDistance: 0,
  lightningStrikeCount: 0,
  battery: 2.62,
  reportInterval: 1,
  localDayRainAccumulation: 2.4,
  feelsLike: 24.1,
  dewPoint: 15.8,
  wetBulbTemperature: 18.2,
  heatIndex: 24.1,
  windChill: 23.4,
  pressureTrend: PressureTrend.Rising,
};

export const stubForecast: ForecastDay[] = [
  {
    dayNum: 18,
    monthNum: 2,
    conditions: 'Partly Cloudy',
    icon: 'partly-cloudy-day',
    airTempHigh: 26.0,
    airTempLow: 14.0,
    precipProbability: 10,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) - 3600 * 5,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 5,
  },
  {
    dayNum: 19,
    monthNum: 2,
    conditions: 'Mostly Sunny',
    icon: 'clear-day',
    airTempHigh: 28.0,
    airTempLow: 15.0,
    precipProbability: 5,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 19,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 29,
  },
  {
    dayNum: 20,
    monthNum: 2,
    conditions: 'Thunderstorms',
    icon: 'thunderstorm',
    airTempHigh: 24.0,
    airTempLow: 16.0,
    precipProbability: 70,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 43,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 53,
  },
  {
    dayNum: 21,
    monthNum: 2,
    conditions: 'Rainy',
    icon: 'rainy',
    airTempHigh: 19.0,
    airTempLow: 13.0,
    precipProbability: 85,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 67,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 77,
  },
  {
    dayNum: 22,
    monthNum: 2,
    conditions: 'Clearing',
    icon: 'partly-cloudy-day',
    airTempHigh: 22.0,
    airTempLow: 11.0,
    precipProbability: 25,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 91,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 101,
  },
  {
    dayNum: 23,
    monthNum: 2,
    conditions: 'Sunny',
    icon: 'clear-day',
    airTempHigh: 25.0,
    airTempLow: 12.0,
    precipProbability: 0,
    precipType: 'none',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 115,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 125,
  },
  {
    dayNum: 24,
    monthNum: 2,
    conditions: 'Windy',
    icon: 'windy',
    airTempHigh: 27.0,
    airTempLow: 14.0,
    precipProbability: 15,
    precipType: 'rain',
    sunrise: Math.floor(Date.now() / 1000) + 3600 * 139,
    sunset: Math.floor(Date.now() / 1000) + 3600 * 149,
  },
];

export const stubHourlyForecast: HourlyForecast[] = Array.from({ length: 24 }, (_, i) => ({
  timestamp: Math.floor(Date.now() / 1000) + i * 3600,
  conditions: i < 6 ? 'Clear' : i < 12 ? 'Partly Cloudy' : i < 18 ? 'Cloudy' : 'Clear',
  icon: i < 6 ? 'clear-night' : i < 12 ? 'partly-cloudy-day' : i < 18 ? 'cloudy' : 'clear-night',
  airTemperature: 18 + Math.sin((i / 24) * Math.PI * 2 - Math.PI / 2) * 6,
  feelsLike: 17.5 + Math.sin((i / 24) * Math.PI * 2 - Math.PI / 2) * 6.5,
  relativeHumidity: 55 + Math.cos((i / 24) * Math.PI * 2) * 20,
  windAvg: 1.5 + Math.random() * 3,
  windDirection: 180 + Math.floor(Math.random() * 90),
  windGust: 3 + Math.random() * 5,
  precipProbability: i >= 12 && i <= 16 ? 30 + Math.random() * 40 : Math.random() * 10,
  uvIndex: i >= 6 && i <= 18 ? Math.sin(((i - 6) / 12) * Math.PI) * 8 : 0,
}));

export const stubStationStatus: StationStatus = {
  isOnline: true,
  lastReport: Date.now() / 1000 - 45,
  batteryLevel: 2.62,
  signalStrength: 3,
  firmwareVersion: 'v1.7.2',
};
